package ch.pproject.vms.shared.core.team;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("fc53cbf8-8a1a-4efd-be0e-2612a7fa27d7-formdata")
@Generated(value = "ch.pproject.vms.client.core.team.TeamTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class TeamTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public TeamTableRowData addRow() {
    return (TeamTableRowData) super.addRow();
  }

  @Override
  public TeamTableRowData addRow(int rowState) {
    return (TeamTableRowData) super.addRow(rowState);
  }

  @Override
  public TeamTableRowData createRow() {
    return new TeamTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return TeamTableRowData.class;
  }

  @Override
  public TeamTableRowData[] getRows() {
    return (TeamTableRowData[]) super.getRows();
  }

  @Override
  public TeamTableRowData rowAt(int index) {
    return (TeamTableRowData) super.rowAt(index);
  }

  public void setRows(TeamTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class TeamTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String teamNr = "teamNr";
    public static final String name = "name";
    public static final String licenceType = "licenceType";
    public static final String teamMembers = "teamMembers";
    private Long m_teamNr;
    private String m_name;
    private Long m_licenceType;
    private String m_teamMembers;

    public Long getTeamNr() {
      return m_teamNr;
    }

    public void setTeamNr(Long newTeamNr) {
      m_teamNr = newTeamNr;
    }

    public String getName() {
      return m_name;
    }

    public void setName(String newName) {
      m_name = newName;
    }

    public Long getLicenceType() {
      return m_licenceType;
    }

    public void setLicenceType(Long newLicenceType) {
      m_licenceType = newLicenceType;
    }

    public String getTeamMembers() {
      return m_teamMembers;
    }

    public void setTeamMembers(String newTeamMembers) {
      m_teamMembers = newTeamMembers;
    }
  }
}
