package ch.pproject.vms.shared.core.team;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("04ccdee3-fc0d-4482-b1ee-73969c6932a1-formdata")
@Generated(value = "ch.pproject.vms.client.core.team.TeamMemberForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class TeamMemberFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Person getPerson() {
    return getFieldByClass(Person.class);
  }

  public ShirtNumber getShirtNumber() {
    return getFieldByClass(ShirtNumber.class);
  }

  /**
   * access method for property TeamNr.
   */
  public Long getTeamNr() {
    return getTeamNrProperty().getValue();
  }

  /**
   * access method for property TeamNr.
   */
  public void setTeamNr(Long teamNr) {
    getTeamNrProperty().setValue(teamNr);
  }

  public TeamNrProperty getTeamNrProperty() {
    return getPropertyByClass(TeamNrProperty.class);
  }

  @ClassId("9ec8f2b8-dd69-4760-bd0b-342488e45d8a-formdata")
  public static class Person extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("bd38fd22-6cbe-446f-bcdb-154ea718a076-formdata")
  public static class ShirtNumber extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class TeamNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }
}
