package ch.pproject.vms.shared.core.person;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("a6e19751-3367-4fd4-b1a1-8182e576fd39-formdata")
@Generated(value = "ch.pproject.vms.client.core.person.AbstractPersonTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractPersonTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public AbstractPersonTableRowData addRow() {
    return (AbstractPersonTableRowData) super.addRow();
  }

  @Override
  public AbstractPersonTableRowData addRow(int rowState) {
    return (AbstractPersonTableRowData) super.addRow(rowState);
  }

  @Override
  public abstract AbstractPersonTableRowData createRow();

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return AbstractPersonTableRowData.class;
  }

  @Override
  public AbstractPersonTableRowData[] getRows() {
    return (AbstractPersonTableRowData[]) super.getRows();
  }

  @Override
  public AbstractPersonTableRowData rowAt(int index) {
    return (AbstractPersonTableRowData) super.rowAt(index);
  }

  public void setRows(AbstractPersonTableRowData[] rows) {
    super.setRows(rows);
  }

  public abstract static class AbstractPersonTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String id = "id";
    public static final String name = "name";
    public static final String firstName = "firstName";
    public static final String sex = "sex";
    public static final String dateOfBirth = "dateOfBirth";
    public static final String street = "street";
    public static final String zip = "zip";
    public static final String city = "city";
    public static final String phonePrivate = "phonePrivate";
    public static final String phoneMobile = "phoneMobile";
    public static final String phoneWork = "phoneWork";
    public static final String eMailAddress = "eMailAddress";
    public static final String contactByEmail = "contactByEmail";
    private Long m_id;
    private String m_name;
    private String m_firstName;
    private Long m_sex;
    private Date m_dateOfBirth;
    private String m_street;
    private String m_zip;
    private String m_city;
    private String m_phonePrivate;
    private String m_phoneMobile;
    private String m_phoneWork;
    private String m_eMailAddress;
    private Boolean m_contactByEmail;

    public Long getId() {
      return m_id;
    }

    public void setId(Long newId) {
      m_id = newId;
    }

    public String getName() {
      return m_name;
    }

    public void setName(String newName) {
      m_name = newName;
    }

    public String getFirstName() {
      return m_firstName;
    }

    public void setFirstName(String newFirstName) {
      m_firstName = newFirstName;
    }

    public Long getSex() {
      return m_sex;
    }

    public void setSex(Long newSex) {
      m_sex = newSex;
    }

    public Date getDateOfBirth() {
      return m_dateOfBirth;
    }

    public void setDateOfBirth(Date newDateOfBirth) {
      m_dateOfBirth = newDateOfBirth;
    }

    public String getStreet() {
      return m_street;
    }

    public void setStreet(String newStreet) {
      m_street = newStreet;
    }

    public String getZip() {
      return m_zip;
    }

    public void setZip(String newZip) {
      m_zip = newZip;
    }

    public String getCity() {
      return m_city;
    }

    public void setCity(String newCity) {
      m_city = newCity;
    }

    public String getPhonePrivate() {
      return m_phonePrivate;
    }

    public void setPhonePrivate(String newPhonePrivate) {
      m_phonePrivate = newPhonePrivate;
    }

    public String getPhoneMobile() {
      return m_phoneMobile;
    }

    public void setPhoneMobile(String newPhoneMobile) {
      m_phoneMobile = newPhoneMobile;
    }

    public String getPhoneWork() {
      return m_phoneWork;
    }

    public void setPhoneWork(String newPhoneWork) {
      m_phoneWork = newPhoneWork;
    }

    public String getEMailAddress() {
      return m_eMailAddress;
    }

    public void setEMailAddress(String newEMailAddress) {
      m_eMailAddress = newEMailAddress;
    }

    public Boolean getContactByEmail() {
      return m_contactByEmail;
    }

    public void setContactByEmail(Boolean newContactByEmail) {
      m_contactByEmail = newContactByEmail;
    }
  }
}
