package ch.pproject.vms.shared.core.person;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("3e24a0ec-07d0-4b0e-affa-2bf1a0f1547d-formdata")
@Generated(value = "ch.pproject.vms.client.core.person.ActiveMemberTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ActiveMemberTablePageData extends AbstractPersonTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public ActiveMemberTableRowData addRow() {
    return (ActiveMemberTableRowData) super.addRow();
  }

  @Override
  public ActiveMemberTableRowData addRow(int rowState) {
    return (ActiveMemberTableRowData) super.addRow(rowState);
  }

  @Override
  public ActiveMemberTableRowData createRow() {
    return new ActiveMemberTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return ActiveMemberTableRowData.class;
  }

  @Override
  public ActiveMemberTableRowData[] getRows() {
    return (ActiveMemberTableRowData[]) super.getRows();
  }

  @Override
  public ActiveMemberTableRowData rowAt(int index) {
    return (ActiveMemberTableRowData) super.rowAt(index);
  }

  public void setRows(ActiveMemberTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class ActiveMemberTableRowData extends AbstractPersonTableRowData {

    private static final long serialVersionUID = 1L;
  }
}
