package ch.pproject.vms.shared.core.person;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("c4629f2e-26db-4349-b347-40f4f8e7214c-formdata")
@Generated(value = "ch.pproject.vms.client.core.person.AllPersonTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AllPersonTablePageData extends AbstractPersonTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public AllPersonTableRowData addRow() {
    return (AllPersonTableRowData) super.addRow();
  }

  @Override
  public AllPersonTableRowData addRow(int rowState) {
    return (AllPersonTableRowData) super.addRow(rowState);
  }

  @Override
  public AllPersonTableRowData createRow() {
    return new AllPersonTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return AllPersonTableRowData.class;
  }

  @Override
  public AllPersonTableRowData[] getRows() {
    return (AllPersonTableRowData[]) super.getRows();
  }

  @Override
  public AllPersonTableRowData rowAt(int index) {
    return (AllPersonTableRowData) super.rowAt(index);
  }

  public void setRows(AllPersonTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class AllPersonTableRowData extends AbstractPersonTableRowData {

    private static final long serialVersionUID = 1L;
  }
}
