package ch.pproject.vms.shared.core.person;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldBeanData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("56403a66-0945-449f-8d9e-95924321e7c6-formdata")
@Generated(value = "ch.pproject.vms.client.core.person.PersonForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PersonFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public City getCity() {
    return getFieldByClass(City.class);
  }

  public DateOfBirth getDateOfBirth() {
    return getFieldByClass(DateOfBirth.class);
  }

  public EMailAddress getEMailAddress() {
    return getFieldByClass(EMailAddress.class);
  }

  public FirstName getFirstName() {
    return getFieldByClass(FirstName.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public Notes getNotes() {
    return getFieldByClass(Notes.class);
  }

  /**
   * access method for property PersonNr.
   */
  public Long getPersonNr() {
    return getPersonNrProperty().getValue();
  }

  /**
   * access method for property PersonNr.
   */
  public void setPersonNr(Long personNr) {
    getPersonNrProperty().setValue(personNr);
  }

  public PersonNrProperty getPersonNrProperty() {
    return getPropertyByClass(PersonNrProperty.class);
  }

  public PhoneMobile getPhoneMobile() {
    return getFieldByClass(PhoneMobile.class);
  }

  public PhonePrivate getPhonePrivate() {
    return getFieldByClass(PhonePrivate.class);
  }

  public PhoneWork getPhoneWork() {
    return getFieldByClass(PhoneWork.class);
  }

  public PlayerLicenseNumber getPlayerLicenseNumber() {
    return getFieldByClass(PlayerLicenseNumber.class);
  }

  public RefereeLicenseNumber getRefereeLicenseNumber() {
    return getFieldByClass(RefereeLicenseNumber.class);
  }

  public Roles getRoles() {
    return getFieldByClass(Roles.class);
  }

  public Sex getSex() {
    return getFieldByClass(Sex.class);
  }

  public Street getStreet() {
    return getFieldByClass(Street.class);
  }

  public Zip getZip() {
    return getFieldByClass(Zip.class);
  }

  @ClassId("66205952-d9d7-44f0-aa8d-32b9a5caf4d1-formdata")
  public static class City extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("e23e0462-49b5-4d69-9385-4768906c505d-formdata")
  public static class DateOfBirth extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("f9e3b47b-6de4-49d2-bc6a-42b4f9cdfea4-formdata")
  public static class EMailAddress extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("366786ef-2c71-49cd-920e-74a02db6680d-formdata")
  public static class FirstName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("e36426b0-4b22-45ab-99d9-9b1b61c669cb-formdata")
  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("4dacccf6-b3e6-41af-b1bc-4777f632cbd2-formdata")
  public static class Notes extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class PersonNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("a7c2bc41-5a0f-4fb4-b495-76411085d428-formdata")
  public static class PhoneMobile extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("043774ad-a5e0-4cb7-b1e0-95674223c69c-formdata")
  public static class PhonePrivate extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("da65a565-52a8-4fff-b349-79a8d88050b0-formdata")
  public static class PhoneWork extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class PlayerLicenseNumber extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class RefereeLicenseNumber extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("66944426-ac7d-4076-ac84-40f4b2aee526-formdata")
  public static class Roles extends AbstractTableFieldBeanData {

    private static final long serialVersionUID = 1L;

    @Override
    public RolesRowData addRow() {
      return (RolesRowData) super.addRow();
    }

    @Override
    public RolesRowData addRow(int rowState) {
      return (RolesRowData) super.addRow(rowState);
    }

    @Override
    public RolesRowData createRow() {
      return new RolesRowData();
    }

    @Override
    public Class<? extends AbstractTableRowData> getRowType() {
      return RolesRowData.class;
    }

    @Override
    public RolesRowData[] getRows() {
      return (RolesRowData[]) super.getRows();
    }

    @Override
    public RolesRowData rowAt(int index) {
      return (RolesRowData) super.rowAt(index);
    }

    public void setRows(RolesRowData[] rows) {
      super.setRows(rows);
    }

    public static class RolesRowData extends AbstractTableRowData {

      private static final long serialVersionUID = 1L;
      public static final String role = "role";
      public static final String from = "from";
      public static final String to = "to";
      public static final String notes = "notes";
      private Long m_role;
      private Date m_from;
      private Date m_to;
      private String m_notes;

      public Long getRole() {
        return m_role;
      }

      public void setRole(Long newRole) {
        m_role = newRole;
      }

      public Date getFrom() {
        return m_from;
      }

      public void setFrom(Date newFrom) {
        m_from = newFrom;
      }

      public Date getTo() {
        return m_to;
      }

      public void setTo(Date newTo) {
        m_to = newTo;
      }

      public String getNotes() {
        return m_notes;
      }

      public void setNotes(String newNotes) {
        m_notes = newNotes;
      }
    }
  }

  @ClassId("0d7863da-6298-464d-a43f-99f2eb16f9df-formdata")
  public static class Sex extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("c720b518-c783-4d00-8285-559b1205a335-formdata")
  public static class Street extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("b98946c4-00b2-4802-b2b2-64505d03c5b0-formdata")
  public static class Zip extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
