package ch.pproject.vms.shared.core.person;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("2930a1d6-4d98-4cb7-a923-f59ce822b05e-formdata")
@Generated(value = "ch.pproject.vms.client.core.person.RoleForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class RoleFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Notes getNotes() {
    return getFieldByClass(Notes.class);
  }

  public PeriodFrom getPeriodFrom() {
    return getFieldByClass(PeriodFrom.class);
  }

  public PeriodTo getPeriodTo() {
    return getFieldByClass(PeriodTo.class);
  }

  public Person getPerson() {
    return getFieldByClass(Person.class);
  }

  public Role getRole() {
    return getFieldByClass(Role.class);
  }

  /**
   * access method for property RoleNr.
   */
  public Long getRoleNr() {
    return getRoleNrProperty().getValue();
  }

  /**
   * access method for property RoleNr.
   */
  public void setRoleNr(Long roleNr) {
    getRoleNrProperty().setValue(roleNr);
  }

  public RoleNrProperty getRoleNrProperty() {
    return getPropertyByClass(RoleNrProperty.class);
  }

  @ClassId("53e3e0aa-6cca-40df-ada7-305ce0fa12ef-formdata")
  public static class Notes extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("60312fe6-a7a5-45b7-883c-a7d7a81c1eb0-formdata")
  public static class PeriodFrom extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("47df9855-10f5-4102-8749-6f3b971d5413-formdata")
  public static class PeriodTo extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("20b6e442-0946-4d44-b2ee-78e19dab1547-formdata")
  public static class Person extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("2b920092-af7d-4157-9327-1b1c7cba27eb-formdata")
  public static class Role extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class RoleNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }
}
