package ch.pproject.vms.shared.accounting.posting;

import java.math.BigDecimal;
import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("347bdd3b-99ce-4928-adab-acabacbd708e-formdata")
@Generated(value = "ch.pproject.vms.client.accounting.posting.PostingSearchForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PostingSearchFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Account getAccount() {
    return getFieldByClass(Account.class);
  }

  public AccountRadioButtonGroup getAccountRadioButtonGroup() {
    return getFieldByClass(AccountRadioButtonGroup.class);
  }

  public AccountingYear getAccountingYear() {
    return getFieldByClass(AccountingYear.class);
  }

  public Activity getActivity() {
    return getFieldByClass(Activity.class);
  }

  public AmountFrom getAmountFrom() {
    return getFieldByClass(AmountFrom.class);
  }

  public AmountTo getAmountTo() {
    return getFieldByClass(AmountTo.class);
  }

  public Person getPerson() {
    return getFieldByClass(Person.class);
  }

  public PostingDateFrom getPostingDateFrom() {
    return getFieldByClass(PostingDateFrom.class);
  }

  public PostingDateTo getPostingDateTo() {
    return getFieldByClass(PostingDateTo.class);
  }

  public PostingText getPostingText() {
    return getFieldByClass(PostingText.class);
  }

  public Status getStatus() {
    return getFieldByClass(Status.class);
  }

  public VoucherNo getVoucherNo() {
    return getFieldByClass(VoucherNo.class);
  }

  @ClassId("02aaa45f-d4e0-4576-b04f-76cf0c0b308d-formdata")
  public static class Account extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("6446440f-77fd-47f7-ac10-a62e086aba6c-formdata")
  public static class AccountRadioButtonGroup extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("a988b834-4235-42ed-bf7d-343ab8de7bf5-formdata")
  public static class AccountingYear extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("1a136397-d61a-4a6a-9817-004beee0b9cc-formdata")
  public static class Activity extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("14c4f934-152b-4eee-83a8-e9abd47688d2-formdata")
  public static class AmountFrom extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("07d0612e-9c0a-47ce-b8cd-5e9a53ac8047-formdata")
  public static class AmountTo extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("3015f30c-1202-42f4-8b69-5d0294d78f48-formdata")
  public static class Person extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("1d4cb9b0-226d-4134-a613-22063927be32-formdata")
  public static class PostingDateFrom extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("92b9a406-2429-436a-b012-2f606dae84e6-formdata")
  public static class PostingDateTo extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("69200af1-f08e-41d2-96ef-07121424fff1-formdata")
  public static class PostingText extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("4b2b2003-9ac5-4013-8288-4a32f083ca55-formdata")
  public static class Status extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("6c8a882c-9c8c-4d92-a2a4-f95472511c4e-formdata")
  public static class VoucherNo extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
