package ch.pproject.vms.shared.accounting.posting;

import java.math.BigDecimal;
import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("80d535c5-fc7a-473a-a1df-72376bb08d9c-formdata")
@Generated(value = "ch.pproject.vms.client.accounting.posting.PostingForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PostingFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public AccountingYear getAccountingYear() {
    return getFieldByClass(AccountingYear.class);
  }

  public Activity getActivity() {
    return getFieldByClass(Activity.class);
  }

  public Amount getAmount() {
    return getFieldByClass(Amount.class);
  }

  public CreditAccount getCreditAccount() {
    return getFieldByClass(CreditAccount.class);
  }

  public DebitAccount getDebitAccount() {
    return getFieldByClass(DebitAccount.class);
  }

  public Notes getNotes() {
    return getFieldByClass(Notes.class);
  }

  public Person getPerson() {
    return getFieldByClass(Person.class);
  }

  public PostingDate getPostingDate() {
    return getFieldByClass(PostingDate.class);
  }

  /**
   * access method for property PostingNr.
   */
  public Long getPostingNr() {
    return getPostingNrProperty().getValue();
  }

  /**
   * access method for property PostingNr.
   */
  public void setPostingNr(Long postingNr) {
    getPostingNrProperty().setValue(postingNr);
  }

  public PostingNrProperty getPostingNrProperty() {
    return getPropertyByClass(PostingNrProperty.class);
  }

  public PostingText getPostingText() {
    return getFieldByClass(PostingText.class);
  }

  public Status getStatus() {
    return getFieldByClass(Status.class);
  }

  public VoucherNo getVoucherNo() {
    return getFieldByClass(VoucherNo.class);
  }

  @ClassId("a60193b4-27c9-4cae-8957-e67a201177f5-formdata")
  public static class AccountingYear extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("8ab602f9-6920-4539-ba98-4d0e6a2e5658-formdata")
  public static class Activity extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("e6accf7d-4782-4159-ae21-23a5054c258f-formdata")
  public static class Amount extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("cd30aad1-b7db-43c2-a867-2886174b3086-formdata")
  public static class CreditAccount extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("0b5234a9-cae1-4205-a359-fb8a883c37f0-formdata")
  public static class DebitAccount extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("a7b44d3b-f732-4801-aa4e-cd8e48aa0b19-formdata")
  public static class Notes extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("78986bd0-03bd-4817-acdd-1d833745bb74-formdata")
  public static class Person extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("d7eea383-108e-4b3c-a7e6-41d5a28320ec-formdata")
  public static class PostingDate extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class PostingNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("64f8d4fd-d10f-4f55-8502-07bc2a023fb6-formdata")
  public static class PostingText extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("ca676430-e8e0-4fa2-b51e-fdda1211c891-formdata")
  public static class Status extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("488daf98-1e1c-4d5a-87fa-8a12721c2649-formdata")
  public static class VoucherNo extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
