package ch.pproject.vms.shared.accounting.posting;

import java.math.BigDecimal;
import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.vms.client.accounting.posting.PostingsTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PostingsTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public PostingsTableRowData addRow() {
    return (PostingsTableRowData) super.addRow();
  }

  @Override
  public PostingsTableRowData addRow(int rowState) {
    return (PostingsTableRowData) super.addRow(rowState);
  }

  @Override
  public PostingsTableRowData createRow() {
    return new PostingsTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return PostingsTableRowData.class;
  }

  @Override
  public PostingsTableRowData[] getRows() {
    return (PostingsTableRowData[]) super.getRows();
  }

  @Override
  public PostingsTableRowData rowAt(int index) {
    return (PostingsTableRowData) super.rowAt(index);
  }

  public void setRows(PostingsTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class PostingsTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String postingNr = "postingNr";
    public static final String voucherNo = "voucherNo";
    public static final String postingDate = "postingDate";
    public static final String accountingYear = "accountingYear";
    public static final String debitAccount = "debitAccount";
    public static final String creditAccount = "creditAccount";
    public static final String amount = "amount";
    public static final String postingText = "postingText";
    public static final String status = "status";
    public static final String person = "person";
    public static final String activity = "activity";
    private Long m_postingNr;
    private String m_voucherNo;
    private Date m_postingDate;
    private Long m_accountingYear;
    private String m_debitAccount;
    private String m_creditAccount;
    private BigDecimal m_amount;
    private String m_postingText;
    private Long m_status;
    private Long m_person;
    private String m_activity;

    public Long getPostingNr() {
      return m_postingNr;
    }

    public void setPostingNr(Long newPostingNr) {
      m_postingNr = newPostingNr;
    }

    public String getVoucherNo() {
      return m_voucherNo;
    }

    public void setVoucherNo(String newVoucherNo) {
      m_voucherNo = newVoucherNo;
    }

    public Date getPostingDate() {
      return m_postingDate;
    }

    public void setPostingDate(Date newPostingDate) {
      m_postingDate = newPostingDate;
    }

    public Long getAccountingYear() {
      return m_accountingYear;
    }

    public void setAccountingYear(Long newAccountingYear) {
      m_accountingYear = newAccountingYear;
    }

    public String getDebitAccount() {
      return m_debitAccount;
    }

    public void setDebitAccount(String newDebitAccount) {
      m_debitAccount = newDebitAccount;
    }

    public String getCreditAccount() {
      return m_creditAccount;
    }

    public void setCreditAccount(String newCreditAccount) {
      m_creditAccount = newCreditAccount;
    }

    public BigDecimal getAmount() {
      return m_amount;
    }

    public void setAmount(BigDecimal newAmount) {
      m_amount = newAmount;
    }

    public String getPostingText() {
      return m_postingText;
    }

    public void setPostingText(String newPostingText) {
      m_postingText = newPostingText;
    }

    public Long getStatus() {
      return m_status;
    }

    public void setStatus(Long newStatus) {
      m_status = newStatus;
    }

    public Long getPerson() {
      return m_person;
    }

    public void setPerson(Long newPerson) {
      m_person = newPerson;
    }

    public String getActivity() {
      return m_activity;
    }

    public void setActivity(String newActivity) {
      m_activity = newActivity;
    }
  }
}
