package ch.pproject.vms.shared.accounting.posting;

import java.math.BigDecimal;
import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("4b900592-ff45-43d5-a9ab-d472069175a6-formdata")
@Generated(value = "ch.pproject.vms.client.accounting.posting.PostingsPerAccountTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PostingsPerAccountTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public PostingsPerAccountTableRowData addRow() {
    return (PostingsPerAccountTableRowData) super.addRow();
  }

  @Override
  public PostingsPerAccountTableRowData addRow(int rowState) {
    return (PostingsPerAccountTableRowData) super.addRow(rowState);
  }

  @Override
  public PostingsPerAccountTableRowData createRow() {
    return new PostingsPerAccountTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return PostingsPerAccountTableRowData.class;
  }

  @Override
  public PostingsPerAccountTableRowData[] getRows() {
    return (PostingsPerAccountTableRowData[]) super.getRows();
  }

  @Override
  public PostingsPerAccountTableRowData rowAt(int index) {
    return (PostingsPerAccountTableRowData) super.rowAt(index);
  }

  public void setRows(PostingsPerAccountTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class PostingsPerAccountTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String postingNr = "postingNr";
    public static final String voucherNo = "voucherNo";
    public static final String postingDate = "postingDate";
    public static final String postingTextDebit = "postingTextDebit";
    public static final String amountDebit = "amountDebit";
    public static final String amountCredit = "amountCredit";
    public static final String postingTextCredit = "postingTextCredit";
    public static final String columnSorting = "columnSorting";
    private Long m_postingNr;
    private String m_voucherNo;
    private Date m_postingDate;
    private String m_postingTextDebit;
    private BigDecimal m_amountDebit;
    private BigDecimal m_amountCredit;
    private String m_postingTextCredit;
    private Integer m_columnSorting;

    public Long getPostingNr() {
      return m_postingNr;
    }

    public void setPostingNr(Long newPostingNr) {
      m_postingNr = newPostingNr;
    }

    public String getVoucherNo() {
      return m_voucherNo;
    }

    public void setVoucherNo(String newVoucherNo) {
      m_voucherNo = newVoucherNo;
    }

    public Date getPostingDate() {
      return m_postingDate;
    }

    public void setPostingDate(Date newPostingDate) {
      m_postingDate = newPostingDate;
    }

    public String getPostingTextDebit() {
      return m_postingTextDebit;
    }

    public void setPostingTextDebit(String newPostingTextDebit) {
      m_postingTextDebit = newPostingTextDebit;
    }

    public BigDecimal getAmountDebit() {
      return m_amountDebit;
    }

    public void setAmountDebit(BigDecimal newAmountDebit) {
      m_amountDebit = newAmountDebit;
    }

    public BigDecimal getAmountCredit() {
      return m_amountCredit;
    }

    public void setAmountCredit(BigDecimal newAmountCredit) {
      m_amountCredit = newAmountCredit;
    }

    public String getPostingTextCredit() {
      return m_postingTextCredit;
    }

    public void setPostingTextCredit(String newPostingTextCredit) {
      m_postingTextCredit = newPostingTextCredit;
    }

    public Integer getColumnSorting() {
      return m_columnSorting;
    }

    public void setColumnSorting(Integer newColumnSorting) {
      m_columnSorting = newColumnSorting;
    }
  }
}
