package ch.pproject.vms.shared.core.administration;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("0c0f5319-1bf2-4f0b-a100-16569a8ad7a5-formdata")
@Generated(value = "ch.pproject.vms.client.core.administration.UserTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class UserTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public UserTableRowData addRow() {
    return (UserTableRowData) super.addRow();
  }

  @Override
  public UserTableRowData addRow(int rowState) {
    return (UserTableRowData) super.addRow(rowState);
  }

  @Override
  public UserTableRowData createRow() {
    return new UserTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return UserTableRowData.class;
  }

  @Override
  public UserTableRowData[] getRows() {
    return (UserTableRowData[]) super.getRows();
  }

  @Override
  public UserTableRowData rowAt(int index) {
    return (UserTableRowData) super.rowAt(index);
  }

  public void setRows(UserTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class UserTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String userNr = "userNr";
    public static final String username = "username";
    private Long m_userNr;
    private String m_username;

    public Long getUserNr() {
      return m_userNr;
    }

    public void setUserNr(Long newUserNr) {
      m_userNr = newUserNr;
    }

    public String getUsername() {
      return m_username;
    }

    public void setUsername(String newUsername) {
      m_username = newUsername;
    }
  }
}
