package ch.pproject.vms.shared.core.administration;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("df5ce46e-72a8-46dd-b03e-dee4411600aa-formdata")
@Generated(value = "ch.pproject.vms.client.core.administration.UserPermissionTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class UserPermissionTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public UserPermissionTableRowData addRow() {
    return (UserPermissionTableRowData) super.addRow();
  }

  @Override
  public UserPermissionTableRowData addRow(int rowState) {
    return (UserPermissionTableRowData) super.addRow(rowState);
  }

  @Override
  public UserPermissionTableRowData createRow() {
    return new UserPermissionTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return UserPermissionTableRowData.class;
  }

  @Override
  public UserPermissionTableRowData[] getRows() {
    return (UserPermissionTableRowData[]) super.getRows();
  }

  @Override
  public UserPermissionTableRowData rowAt(int index) {
    return (UserPermissionTableRowData) super.rowAt(index);
  }

  public void setRows(UserPermissionTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class UserPermissionTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String userNr = "userNr";
    public static final String permissionName = "permissionName";
    private Long m_userNr;
    private String m_permissionName;

    public Long getUserNr() {
      return m_userNr;
    }

    public void setUserNr(Long newUserNr) {
      m_userNr = newUserNr;
    }

    public String getPermissionName() {
      return m_permissionName;
    }

    public void setPermissionName(String newPermissionName) {
      m_permissionName = newPermissionName;
    }
  }
}
