CREATE TABLE "APP"."PERSON"
(
   PERSON_NR int PRIMARY KEY NOT NULL,
   NAME varchar(100),
   FIRSTNAME varchar(100),
   SEX int,
   DATEOFBIRTH date,
   STREET varchar(100),
   ZIP varchar(100),
   PLACE varchar(100),
   PHONEPRIVATE varchar(100),
   PHONEWORK varchar(100),
   PHONEMOBILE varchar(100),
   EMAIL varchar(100),
   CONTACTBYEMAIL varchar(100),
   NOTES varchar(1000)
)
;
CREATE UNIQUE INDEX SQL130417182923020 ON "APP"."PERSON"(PERSON_NR)
;


CREATE TABLE "APP"."ROLE"
(
   ROLE_NR int PRIMARY KEY NOT NULL,
   PERSON_NR int NOT NULL,
   ROLE_UID int NOT NULL,
   ENTRYDATE date,
   LEAVINGDATE date
)
;
CREATE UNIQUE INDEX SQL130417182335150 ON "APP"."ROLE"(ROLE_NR)
;


CREATE TABLE "APP"."VMSSEQ"
(
   LAST_VAL int
)
;


INSERT INTO "APP"."VMSSEQ" (LAST_VAL) VALUES (1);
