INSERT INTO TEAM (TEAM_NR, NAME, LICENCE_TYPE_UID)
		VALUES (nextval('vmsseq'), 'Herren KF', 30002);

INSERT INTO TEAM (TEAM_NR, NAME, LICENCE_TYPE_UID)
		VALUES (nextval('vmsseq'), 'Damen KF', 30002);
        
INSERT INTO TEAM (TEAM_NR, NAME, LICENCE_TYPE_UID)
		VALUES (nextval('vmsseq'), 'Juniorinnen B', 30003);
                
INSERT INTO TEAM (TEAM_NR, NAME, LICENCE_TYPE_UID)
		VALUES (nextval('vmsseq'), 'Junioren B', 0);

INSERT INTO PERSON (PERSON_NR, NAME, FIRSTNAME, SEX, DATEOFBIRTH, STREET, ZIP, CITY, PHONEPRIVATE, PHONEWORK, PHONEMOBILE, EMAIL, NOTES)
SELECT nextval('vmsseq'), 'Muster', 'Hans', 20002, '1983-06-11', 'Bahnhofstrasse 26', '8000', 'Zürich', '0448101321', null, null, 'mm@ema.il', null
FROM TEAM T WHERE T.NAME = 'Herren KF';

INSERT INTO ROLE (ROLE_NR, PERSON_NR, ROLE_UID, FROM_DATE) 
SELECT nextval('vmsseq'), PERSON_NR, 10001, '2002-05-01'
FROM PERSON WHERE NAME = 'Muster';

INSERT INTO TEAM_MEMBER (TEAM_NR, PERSON_NR, SHIRT_NUMBER)
SELECT T.TEAM_NR, P.PERSON_NR, 12
FROM TEAM T, PERSON P WHERE T.NAME = 'Herren KF' AND P.NAME = 'Muster';