INSERT INTO ACCOUNTING_YEAR (ACCOUNTING_YEAR_NR, NAME, START_DATE, END_DATE)
		VALUES (nextval('vmsseq'), 'Saison 13/14', '2013-05-09', '2014-05-08');

INSERT INTO ACCOUNT (ACCOUNT_NR, ACCOUNT_NAME, TYPE_UID, DESCRIPTION, ACCOUNTING_YEAR_NR)
		SELECT nextval('vmsseq'), 'Postkonto', 510002, 'Postcheck-Konto 80-1231-4', (SELECT ACCOUNTING_YEAR_NR FROM ACCOUNTING_YEAR WHERE NAME = 'Saison 13/14') FROM DUAL;

INSERT INTO ACCOUNT (ACCOUNT_NR, ACCOUNT_NAME, TYPE_UID, DESCRIPTION, ACCOUNTING_YEAR_NR)
		SELECT nextval('vmsseq'), 'Mitgliederbeitrag', 510011, 'Mitgliederbeitrag (Aktive)', (SELECT ACCOUNTING_YEAR_NR FROM ACCOUNTING_YEAR WHERE NAME = 'Saison 13/14') FROM DUAL;

INSERT INTO POSTING (POSTING_NR, VOUCHER_NO, PERSON_NR, ACTIVITY_NR, ACCOUNTING_YEAR_NR, CREDIT_ACCOUNT_NR, DEBIT_ACCOUNT_NR, AMOUNT, POSTING_DATE, POSTING_TEXT, STATUS_UID)
		SELECT nextval('vmsseq'), '1', (SELECT PERSON_NR FROM PERSON WHERE NAME = 'Muster'), 0, (SELECT ACCOUNTING_YEAR_NR FROM ACCOUNTING_YEAR WHERE NAME = 'Saison 13/14'), (SELECT ACCOUNT_NR FROM ACCOUNT WHERE ACCOUNT_NAME = 'Postkonto'), (SELECT ACCOUNT_NR FROM ACCOUNT WHERE ACCOUNT_NAME = 'Mitgliederbeitrag'), 111.75, '2014-04-28', 'Mitgliederbeitrag Hans Muster', 520001
		FROM DUAL;