DROP TABLE IF EXISTS ACCOUNTING_YEAR;
CREATE TABLE ACCOUNTING_YEAR (
	ACCOUNTING_YEAR_NR int PRIMARY KEY NOT NULL,
	NAME varchar(100),
	START_DATE date,
	END_DATE date,
    IS_CLOSED boolean default false
);

CREATE UNIQUE INDEX ACCOUNTING_YEAR_UIDX1 ON ACCOUNTING_YEAR(ACCOUNTING_YEAR_NR);

DROP TABLE IF EXISTS POSTING;
CREATE TABLE POSTING (
    POSTING_NR int PRIMARY KEY NOT NULL,
    VOUCHER_NO varchar(100),
    PERSON_NR int NOT NULL DEFAULT 0,
    ACTIVITY_NR int NOT NULL DEFAULT 0,
	ACCOUNTING_YEAR_NR int NOT NULL DEFAULT 0,
    CREDIT_ACCOUNT_NR int NOT NULL DEFAULT 0,
    DEBIT_ACCOUNT_NR int NOT NULL DEFAULT 0,
	AMOUNT double NOT NULL,
    POSTING_DATE date,
    POSTING_TEXT varchar(1000),
    STATUS_UID int NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX POSTING_UIDX1 ON POSTING(POSTING_NR);

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
    ACCOUNT_NR int PRIMARY KEY NOT NULL,
    ACCOUNT_NAME varchar(100),
    TYPE_UID int NOT NULL DEFAULT 0,
    DESCRIPTION varchar(1000),
	ACCOUNTING_YEAR_NR int NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX ACCOUNT_UIDX1 ON ACCOUNT(ACCOUNT_NR);