package ch.pproject.vms.shared.core.csv;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldBeanData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("1f223b5e-fd4a-4e33-87b1-e5087ee1fe12-formdata")
@Generated(value = "ch.pproject.vms.client.core.csv.SelectionForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class SelectionFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Selection getSelection() {
    return getFieldByClass(Selection.class);
  }

  @ClassId("3c91a721-c4f8-4571-a76b-a2f4f7688f73-formdata")
  public static class Selection extends AbstractTableFieldBeanData {

    private static final long serialVersionUID = 1L;

    @Override
    public SelectionRowData addRow() {
      return (SelectionRowData) super.addRow();
    }

    @Override
    public SelectionRowData addRow(int rowState) {
      return (SelectionRowData) super.addRow(rowState);
    }

    @Override
    public SelectionRowData createRow() {
      return new SelectionRowData();
    }

    @Override
    public Class<? extends AbstractTableRowData> getRowType() {
      return SelectionRowData.class;
    }

    @Override
    public SelectionRowData[] getRows() {
      return (SelectionRowData[]) super.getRows();
    }

    @Override
    public SelectionRowData rowAt(int index) {
      return (SelectionRowData) super.rowAt(index);
    }

    public void setRows(SelectionRowData[] rows) {
      super.setRows(rows);
    }

    public static class SelectionRowData extends AbstractTableRowData {

      private static final long serialVersionUID = 1L;
      public static final String selection = "selection";
      private Boolean m_selection;

      public Boolean getSelection() {
        return m_selection;
      }

      public void setSelection(Boolean newSelection) {
        m_selection = newSelection;
      }
    }
  }
}
