package ch.pproject.vms.shared.accounting.account;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.vms.client.accounting.account.AccountingYearTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AccountingYearTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public AccountingYearTableRowData addRow() {
    return (AccountingYearTableRowData) super.addRow();
  }

  @Override
  public AccountingYearTableRowData addRow(int rowState) {
    return (AccountingYearTableRowData) super.addRow(rowState);
  }

  @Override
  public AccountingYearTableRowData createRow() {
    return new AccountingYearTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return AccountingYearTableRowData.class;
  }

  @Override
  public AccountingYearTableRowData[] getRows() {
    return (AccountingYearTableRowData[]) super.getRows();
  }

  @Override
  public AccountingYearTableRowData rowAt(int index) {
    return (AccountingYearTableRowData) super.rowAt(index);
  }

  public void setRows(AccountingYearTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class AccountingYearTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String accountingYearNr = "accountingYearNr";
    public static final String name = "name";
    public static final String from = "from";
    public static final String to = "to";
    public static final String closed = "closed";
    private Long m_accountingYearNr;
    private String m_name;
    private Date m_from;
    private Date m_to;
    private Boolean m_closed;

    public Long getAccountingYearNr() {
      return m_accountingYearNr;
    }

    public void setAccountingYearNr(Long newAccountingYearNr) {
      m_accountingYearNr = newAccountingYearNr;
    }

    public String getName() {
      return m_name;
    }

    public void setName(String newName) {
      m_name = newName;
    }

    public Date getFrom() {
      return m_from;
    }

    public void setFrom(Date newFrom) {
      m_from = newFrom;
    }

    public Date getTo() {
      return m_to;
    }

    public void setTo(Date newTo) {
      m_to = newTo;
    }

    public Boolean getClosed() {
      return m_closed;
    }

    public void setClosed(Boolean newClosed) {
      m_closed = newClosed;
    }
  }
}
