package ch.pproject.vms.shared.accounting.account;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.vms.client.accounting.account.AccountForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AccountFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  /**
   * access method for property AccountNr.
   */
  public Long getAccountNr() {
    return getAccountNrProperty().getValue();
  }

  /**
   * access method for property AccountNr.
   */
  public void setAccountNr(Long accountNr) {
    getAccountNrProperty().setValue(accountNr);
  }

  public AccountNrProperty getAccountNrProperty() {
    return getPropertyByClass(AccountNrProperty.class);
  }

  public AccountingYear getAccountingYear() {
    return getFieldByClass(AccountingYear.class);
  }

  public Description getDescription() {
    return getFieldByClass(Description.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public Type getType() {
    return getFieldByClass(Type.class);
  }

  public static class AccountNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class AccountingYear extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Description extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Type extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }
}
